version: '3'

services:
  web:
    image: sample
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
      - bundle:/usr/local/bundle
    container_name: sample_app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 4306:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./env/development/db.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  db-data:
    driver: local

